package com.oracle.strutsdemo.model.bean;
import java.io.Serializable;

/**
 * 杞﹁締鍥剧墖 鍎屽儴鍎栧儖鍎斿儣.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class DrImage implements Serializable{
	private static final long serialVersionUID = 1L;
	
	private Integer imageId;
	private Integer drId;
	private String imagePath;
	
	public DrImage() {
		super();
	}
	
	public Integer getImageId() {
		return imageId;
	}
	public void setImageId(Integer imageId) {
		this.imageId = imageId;
	}
	public Integer getDrId() {
		return drId;
	}
	public void setDrId(Integer drId) {
		this.drId = drId;
	}
	public String getImagePath() {
		return imagePath;
	}
	public void setImagePath(String imagePath) {
		this.imagePath = imagePath;
	}
	
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((imageId == null) ? 0 : imageId.hashCode());

		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		DrImage other = (DrImage) obj;
		if (imageId == null) {
			if (other.imageId != null) {
				return false;
			}
		} else if (!imageId.equals(other.imageId)) {
			return false;
		}

		return true;
	}
	

	
}

