

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for drmessage
-- ----------------------------
DROP TABLE IF EXISTS drmessage;
CREATE TABLE drmessage (
  `DRID` int(11) NOT NULL AUTO_INCREMENT,
  `DRBRAND` varchar(20) NOT NULL,
  `DRSERIES` varchar(20) NOT NULL,
  `DRPRICE` float NOT NULL,
  `DRSALES` int(11) NOT NULL,
  `DRSIZE` varchar(20) NOT NULL,
  `DRNUMBER` int(11) NOT NULL,
  `DRWEIGHT` varchar(20) NOT NULL,
  `DRCLEANLINESS` varchar(20) NOT NULL,
  `DRCOLOR` varchar(20) NOT NULL,
  `DRCUTTING` varchar(20) NOT NULL,
  `DRMATERIAL` varchar(20) NOT NULL,
  `DRFIRSTPICTURE` varchar(100) NOT NULL,
  `DRDESCRIPTION` text NOT NULL,
  `DREXTENSION` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`DRID`)
) ENGINE=MyISAM AUTO_INCREMENT=51 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of drmessage
-- ----------------------------
INSERT INTO drmessage VALUES ('1', '周大福', 'magnis', '37366', '1690', '2*2', '31', '80分', 'VS', 'D', 'VG', '18K玫瑰金', 'images/dr_temp/4.jpg', 'enim fringilla at accumsan laoreet ad Morbi eros Phasellus Praesent turpis auctor feugiat risus tristique scelerisque ad eget nisl eleifend tempus Nam neque Aliquam dolor porta id non libero quis', '');
INSERT INTO drmessage VALUES ('2', '老凤祥', 'eget', '27336', '2326', '2*1', '33', '5分', 'FI', 'J', 'VG', '18K黄金', 'images/dr_temp/3.jpg', 'ipsum arcu pharetra sollicitudin lorem egestas nisi tempus eleifend Aliquam Nunc Curae nibh In nisi sollicitudin Nunc Aenean id enim Integer purus metus imperdiet Quisque Nulla imperdiet facilisis porta ', '');
INSERT INTO drmessage VALUES ('3', '周大福', 'volutpat', '28193', '3572', '2*2', '1', '40分', 'SI', 'K', 'VG', 'PT950', 'images/dr_temp/3.jpg', 'Donec Aliquam Mauris auctor eu commodo lacinia Nulla dui tempor molestie sollicitudin mauris at euismod tristique Pellentesque id nonummy vestibulum pretium malesuada condimentum diam Cum tempus', '');
INSERT INTO drmessage VALUES ('4', '周大福', 'faucibus', '14701', '3981', '2*1', '40', '2克拉', 'VVS', 'Q', 'VG', '18K玫瑰金', 'images/dr_temp/9.jpg', 'enim ad cubilia Vivamus Integer varius arcu vitae euismod interdum pulvinar amet vel netus Ut arcu dapibus ipsum ut magna aliquam lacinia sit senectus tellus Cum leo sit Fusce a', '');
INSERT INTO drmessage VALUES ('5', '老凤祥', 'nonummy', '51426', '1775', '1*1', '97', '10分', 'VS', 'H', 'VG', 'PT950', 'images/dr_temp/5.jpg', 'magnis Lorem ipsum nulla Morbi Aenean ante sociis vestibulum Class netus conubia vehicula nunc mus varius Ut non Vestibulum vel sed viverra semper netus', '');
INSERT INTO drmessage VALUES ('6', '老凤祥', 'suscipit', '53068', '2049', '2*2', '92', '30分', 'VVS', 'K', 'VG', '18K黄金', 'images/dr_temp/8.jpg', 'a ridiculus imperdiet hymenaeos tortor taciti leo massa tempor faucibus mus lacus neque eu odio lectus scelerisque rhoncus justo Integer sodales tristique sit nec Vestibulum egestas Nam', '');
INSERT INTO drmessage VALUES ('7', '周大福', 'Ut', '47505', '9739', '2*2', '96', '5克拉', 'I', 'S', 'G', '18K黄金', 'images/dr_temp/7.jpg', 'malesuada sagittis convallis feugiat aliquet Integer porttitor dapibus eu rhoncus mauris adipiscing ornare velit hendrerit nulla Sed mattis leo placerat Vestibulum Duis fames pharetra', '');
INSERT INTO drmessage VALUES ('8', '周大生', 'laoreet', '21204', '1200', '2*1', '84', '1克拉', 'VVS', 'L', 'G', 'PT950', 'images/dr_temp/0.jpg', 'vitae tristique taciti Ut Maecenas ridiculus vitae purus parturient dignissim vel habitant per tristique ligula tortor pretium vel convallis velit semper Curae pellentesque dignissim aliquam per suscipit tellus congue dui ante facilisi Lorem interdum orci Aenean quis senectus fermentum nulla dignissim venenatis adipiscing Vestibulum et per et dolor', '');
INSERT INTO drmessage VALUES ('9', '周大生', 'montes', '48376', '5629', '2*1', '86', '2克拉', 'VS', 'H', 'VG', 'PT950', 'images/dr_temp/9.jpg', 'elementum inceptos conubia ante gravida morbi Nam hymenaeos conubia ridiculus mollis consequat at dolor mus condimentum ridiculus vitae netus sapien Fusce et dis nec ligula eros eros fames dignissim inceptos sociosqu felis hymenaeos tincidunt elementum enim bibendum', '');
INSERT INTO drmessage VALUES ('10', '周大生', 'nulla', '19112', '4414', '1*1', '43', '5分', 'SI', 'O', 'G', '18K玫瑰金', 'images/dr_temp/1.jpg', 'aliquam Vivamus Fusce aliquam aliquam ultricies Sed mus metus lobortis netus Cras dolor taciti imperdiet Mauris velit Integer dis a nisi mollis tellus pretium elementum ipsum Aliquam torquent torquent adipiscing sit risus interdum lectus gravida varius feugiat', '');
INSERT INTO drmessage VALUES ('11', '周大生', 'nonummy', '14259', '7339', '2*2', '5', '5分', 'FI', 'I', 'VG', '18K玫瑰金', 'images/dr_temp/4.jpg', 'eros scelerisque placerat ligula lacus interdum viverra natoque egestas amet massa sed egestas at interdum sed volutpat nulla orci luctus Nulla elementum Duis nisi Morbi luctus sit metus Quisque viverra fringilla ullamcorper pede malesuada augue Aliquam cursus mattis scelerisque consequat Aliquam', '');
INSERT INTO drmessage VALUES ('12', '老凤祥', 'tellus', '8593', '7187', '1*1', '1', '2克拉', 'FI', 'G', 'VG', '18K黄金', 'images/dr_temp/6.jpg', 'Nulla vel volutpat massa nonummy nonummy Nam est nostra nisl blandit Duis eu conubia Phasellus Nam netus montes ipsum diam fames neque', '');
INSERT INTO drmessage VALUES ('13', '周大福', 'Vestibulum', '68108', '1079', '1*2', '95', '10分', 'I', 'O', 'VG', '18K黄金', 'images/dr_temp/9.jpg', 'hymenaeos lacus condimentum fringilla commodo viverra risus nisl morbi cubilia dapibus ligula massa congue Fusce ipsum pharetra fringilla Proin iaculis Ut primis rhoncus posuere fringilla Lorem netus Proin facilisi habitant Fusce eget lacus tempus Nunc tortor porta tempus gravida nulla interdum Quisque Class montes Morbi Etiam consequat', '');
INSERT INTO drmessage VALUES ('14', '周大生', 'purus', '63386', '8408', '2*1', '14', '2克拉', 'FI', 'N', 'VG', '18K黄金', 'images/dr_temp/2.jpg', 'tempus sociosqu lacus Pellentesque risus quam Phasellus primis vel lacus elit elementum molestie ultricies ultrices diam placerat nunc mus elementum facilisis iaculis id Integer Pellentesque netus ad consequat congue Aliquam pellentesque Aenean felis eu nonummy inceptos tempor malesuada arcu Donec Proin eget dui mauris morbi Etiam pretium quam Sed Phasellus', '');
INSERT INTO drmessage VALUES ('15', '周大福', 'facilisis', '37214', '7737', '2*2', '44', '1克拉', 'VVS', 'K', 'G', '18K黄金', 'images/dr_temp/5.jpg', 'malesuada pretium Vivamus placerat montes pede tempor felis dignissim vestibulum ligula nisi Ut ad aliquet diam commodo diam parturient imperdiet id suscipit elit eleifend rutrum parturient venenatis massa a convallis cursus conubia tortor Morbi fringilla Pellentesque litora odio Praesent Suspendisse purus vulputate ultrices egestas Quisque', '');
INSERT INTO drmessage VALUES ('16', '老凤祥', 'vitae', '49534', '4488', '1*2', '87', '10分', 'VS', 'K', 'G', '18K玫瑰金', 'images/dr_temp/2.jpg', 'fringilla leo Nam varius vestibulum nibh sollicitudin Vivamus congue tellus Curae magnis dignissim eu Vestibulum urna Cum ullamcorper malesuada ornare penatibus Pellentesque sagittis ultricies dolor Maecenas justo gravida parturient', '');
INSERT INTO drmessage VALUES ('17', '周大生', 'pretium', '26375', '8044', '2*2', '62', '50分', 'I', 'P', 'VG', '18K黄金', 'images/dr_temp/0.jpg', 'Nam lacus ante Praesent facilisi sociis vitae tortor venenatis dignissim posuere dapibus egestas vehicula litora tellus Fusce neque ipsum Praesent augue congue felis non hymenaeos Curae convallis tempus varius vestibulum odio montes pellentesque convallis Praesent ad sapien justo pede faucibus hendrerit Curabitur pede porta Mauris bibendum interdum', '');
INSERT INTO drmessage VALUES ('18', '周大福', 'facilisis', '81963', '1043', '2*1', '62', '20分', 'I', 'R', 'VG', '18K白金', 'images/dr_temp/7.jpg', 'penatibus natoque interdum ligula nisi facilisis Fusce vulputate eleifend Nulla hendrerit Etiam vitae fermentum vulputate dictum taciti nisl adipiscing malesuada eros sociosqu nec per purus egestas Nam', '');
INSERT INTO drmessage VALUES ('19', '老凤祥', 'Vestibulum', '84690', '6949', '1*2', '48', '5克拉', 'SI', 'M', 'G', 'PT950', 'images/dr_temp/7.jpg', 'vulputate metus morbi nulla Lorem suscipit Nunc mauris euismod Nullam sodales convallis condimentum Vivamus pede consequat erat nisi Nulla Cras Class Sed pellentesque urna cursus ultricies taciti sem suscipit ad eu Pellentesque quis lorem varius urna velit Phasellus amet vitae eu justo imperdiet pede hendrerit ante', '');
INSERT INTO drmessage VALUES ('20', '周大福', 'senectus', '26086', '568', '2*2', '96', '50分', 'SI', 'Q', 'VG', '18K玫瑰金', 'images/dr_temp/5.jpg', 'posuere ligula Integer aliquet massa Morbi porta lorem eget Mauris netus primis taciti pharetra sociosqu purus sed elementum adipiscing sociis tellus feugiat metus Praesent dignissim enim Aenean Maecenas et velit pellentesque non Aenean purus leo Nam', '');
INSERT INTO drmessage VALUES ('21', '老凤祥', 'aptent', '20384', '385', '1*2', '21', '80分', 'VVS', 'E', 'G', '18K白金', 'images/dr_temp/0.jpg', 'urna blandit egestas Class Aenean elit faucibus Curabitur blandit felis Ut eget justo nisi vitae dictum cursus mollis mauris quis magnis consequat aliquet faucibus dignissim lacinia varius accumsan leo Proin adipiscing in aliquet urna justo quam ultricies Quisque In posuere', '');
INSERT INTO drmessage VALUES ('22', '老凤祥', 'malesuada', '14757', '3677', '2*1', '90', '50分', 'I', 'M', 'G', '18K玫瑰金', 'images/dr_temp/5.jpg', 'morbi ultricies cubilia Nam nostra aptent cubilia leo amet placerat augue sodales dolor interdum Nullam per vitae nulla scelerisque facilisi vitae', '');
INSERT INTO drmessage VALUES ('23', '周大生', 'Pellentesque', '84080', '905', '1*1', '76', '40分', 'VVS', 'D', 'VG', '18K玫瑰金', 'images/dr_temp/2.jpg', 'Cras nostra nunc lorem Aenean ut cursus risus nonummy velit conubia taciti est interdum Sed magnis quis interdum velit laoreet Ut consequat cubilia nec ornare interdum luctus placerat at leo conubia Mauris tristique Maecenas eros Pellentesque nulla vestibulum risus sagittis pharetra dolor at enim elit ad tempus', '');
INSERT INTO drmessage VALUES ('24', '周大生', 'sociis', '34029', '8559', '1*2', '91', '50分', 'SI', 'D', 'G', '18K玫瑰金', 'images/dr_temp/0.jpg', 'gravida bibendum pulvinar semper condimentum diam purus semper ante tincidunt Curabitur sapien cubilia eu Nulla velit Ut quis non porttitor suscipit auctor parturient Morbi sem felis dis mollis senectus vulputate elit accumsan arcu semper velit facilisis fringilla velit ridiculus sit Cras vitae', '');
INSERT INTO drmessage VALUES ('25', '周大生', 'fringilla', '86379', '8147', '1*2', '12', '30分', 'I', 'Q', 'G', '18K玫瑰金', 'images/dr_temp/8.jpg', 'iaculis Proin sociosqu euismod feugiat ullamcorper commodo purus sociosqu hymenaeos nisl nisi orci facilisi torquent montes dignissim erat tincidunt nonummy habitant est ac turpis dapibus porttitor nec risus non Cum primis Suspendisse Nam hymenaeos urna eget diam ante tincidunt enim per sociosqu volutpat', '');
INSERT INTO drmessage VALUES ('26', '老凤祥', 'ipsum', '24344', '2021', '1*2', '28', '10分', 'VVS', 'I', 'G', '18K玫瑰金', 'images/dr_temp/7.jpg', 'nec nostra Mauris mollis feugiat tincidunt senectus porttitor cursus montes consectetuer vel Cras tortor torquent accumsan et sapien cursus vulputate rutrum aliquet Vivamus felis dis vestibulum interdum adipiscing mollis varius feugiat ultrices primis augue consequat bibendum In laoreet', '');
INSERT INTO drmessage VALUES ('27', '老凤祥', 'tristique', '61705', '7802', '1*1', '79', '5克拉', 'VVS', 'O', 'VG', '18K玫瑰金', 'images/dr_temp/8.jpg', 'feugiat enim Etiam Cras pretium rhoncus dis nisl mollis ultrices Etiam felis eleifend Ut pede ullamcorper blandit conubia interdum lectus consequat Curae blandit amet Aliquam dui sem fermentum amet ornare vehicula porta purus nec Cum adipiscing odio mauris penatibus pellentesque ac nisl eu Sed consequat Curae id', '');
INSERT INTO drmessage VALUES ('28', '周大福', 'feugiat', '65769', '8835', '2*1', '41', '5分', 'VS', 'S', 'G', '18K黄金', 'images/dr_temp/5.jpg', 'nascetur dapibus mattis dolor lectus neque sed est arcu ridiculus purus porta volutpat nunc urna sit nascetur varius convallis sit pellentesque ac', '');
INSERT INTO drmessage VALUES ('29', '周大生', 'Nam', '882', '2410', '2*2', '77', '10分', 'SI', 'S', 'VG', '18K白金', 'images/dr_temp/2.jpg', 'congue sodales augue pretium lorem parturient natoque sociis eros condimentum orci leo Phasellus orci diam torquent in rutrum morbi diam fermentum bibendum sodales Vestibulum felis dapibus id pretium mi', '');
INSERT INTO drmessage VALUES ('30', '周大福', 'vitae', '11527', '7052', '2*2', '36', '30分', 'VS', 'K', 'VG', '18K玫瑰金', 'images/dr_temp/2.jpg', 'ligula Sed nisi id Proin morbi posuere nibh nascetur ornare ridiculus Nam sagittis posuere Aenean non quam Nullam penatibus nisl Quisque at Cum ante ligula Donec convallis lacinia Mauris quis gravida', '');
INSERT INTO drmessage VALUES ('31', '周大福', 'velit', '72677', '5939', '2*2', '43', '40分', 'VS', 'G', 'G', '18K白金', 'images/dr_temp/8.jpg', 'nisl vel suscipit Vivamus nisi egestas Pellentesque nec varius pretium vitae nec sed auctor Praesent aliquam primis cubilia nostra lacinia habitant viverra Morbi posuere euismod eros tempor eu faucibus vehicula ac', '');
INSERT INTO drmessage VALUES ('32', '周大福', 'sem', '85289', '1536', '1*1', '93', '1克拉', 'IF', 'K', 'G', '18K黄金', 'images/dr_temp/5.jpg', 'Aenean justo posuere molestie Quisque lectus luctus Nullam varius nec cursus lacinia nec et lorem pede natoque nostra elementum congue vel vestibulum fames Lorem sapien magnis tortor Nunc non nibh Donec a velit tristique Lorem ridiculus interdum Quisque sed Class pharetra elementum tempor scelerisque luctus aliquam consequat tristique ante nec', '');
INSERT INTO drmessage VALUES ('33', '周大福', 'leo', '98530', '9239', '2*1', '92', '40分', 'FI', 'O', 'G', '18K玫瑰金', 'images/dr_temp/1.jpg', 'justo nonummy nostra Fusce lacinia auctor magna netus Aliquam Praesent dapibus convallis interdum enim id suscipit Phasellus litora velit Suspendisse Cras Nulla tellus vel ipsum tincidunt sapien hendrerit vitae bibendum nisl Praesent taciti Cras vestibulum amet parturient bibendum Lorem viverra et urna posuere lorem imperdiet odio Nunc porta', '');
INSERT INTO drmessage VALUES ('34', '周大生', 'hymenaeos', '70844', '2484', '2*2', '48', '30分', 'I', 'G', 'G', '18K黄金', 'images/dr_temp/2.jpg', 'pulvinar dapibus venenatis tellus mus Curae fringilla Nam ipsum augue quam pretium pulvinar Aenean ullamcorper fringilla Pellentesque quis sodales Class euismod bibendum non condimentum elementum pellentesque Cum netus elementum Ut fringilla Lorem facilisis Vestibulum ipsum natoque elit blandit', '');
INSERT INTO drmessage VALUES ('35', '周大福', 'facilisi', '49129', '3127', '1*2', '18', '2克拉', 'VVS', 'M', 'VG', '18K白金', 'images/dr_temp/7.jpg', 'lorem ornare Proin netus velit vitae cursus montes cubilia auctor fames facilisi felis condimentum dis malesuada nibh felis molestie egestas eros ad congue sem volutpat Vivamus malesuada elementum Proin nibh nunc fermentum', '');
INSERT INTO drmessage VALUES ('36', '周大福', 'sapien', '25516', '2099', '2*2', '97', '80分', 'FI', 'R', 'VG', '18K黄金', 'images/dr_temp/7.jpg', 'Class arcu odio Curabitur interdum pellentesque justo montes urna Morbi Nullam vel Lorem nonummy ridiculus Quisque quis Vestibulum venenatis interdum facilisis nisi imperdiet dui pharetra venenatis ut amet accumsan amet dictum turpis nulla turpis turpis pulvinar aliquet imperdiet turpis', '');
INSERT INTO drmessage VALUES ('37', '周大生', 'magna', '71449', '1739', '2*1', '68', '20分', 'IF', 'R', 'G', '18K黄金', 'images/dr_temp/8.jpg', 'Ut mi Curabitur velit sollicitudin lacus convallis eu sodales Class augue ante vestibulum massa Suspendisse inceptos egestas dis auctor Curae lorem sociosqu venenatis elementum blandit varius tortor congue laoreet lacinia sociis quis Vivamus ante morbi posuere leo Lorem commodo consectetuer penatibus magna turpis posuere', '');
INSERT INTO drmessage VALUES ('38', '周大福', 'libero', '57404', '1260', '2*1', '9', '2克拉', 'SI', 'J', 'G', '18K黄金', 'images/dr_temp/7.jpg', 'Fusce eleifend Praesent odio torquent nec volutpat leo mus nec pellentesque consectetuer ad Class ac amet Quisque Cras laoreet mus lacus torquent sapien metus facilisi libero hendrerit hendrerit pharetra erat Nullam Nulla et placerat convallis laoreet Praesent nibh fringilla facilisi Nullam sociis sem diam vulputate Cras', '');
INSERT INTO drmessage VALUES ('39', '周大生', 'In', '40763', '3217', '2*2', '80', '2克拉', 'IF', 'O', 'G', '18K白金', 'images/dr_temp/2.jpg', 'vestibulum ridiculus nibh nisl porttitor aliquet In convallis Proin ut dictum elit semper blandit et auctor velit nostra Class penatibus conubia risus Fusce Nullam augue volutpat aptent hymenaeos condimentum fames vel Curae Praesent tellus Quisque laoreet lacus tincidunt Duis risus sed dictum porta', '');
INSERT INTO drmessage VALUES ('40', '周大福', 'est', '57155', '7641', '1*2', '54', '5克拉', 'I', 'E', 'VG', '18K玫瑰金', 'images/dr_temp/4.jpg', 'dapibus Class ultricies ultrices tempor penatibus Nulla lacinia justo facilisis elit elit tellus dictum ridiculus Aenean elementum Ut Cras non laoreet Quisque nostra libero nostra eget Nunc tincidunt blandit pede et ultricies', '');
INSERT INTO drmessage VALUES ('41', '周大生', 'Integer', '53085', '4967', '2*1', '20', '2克拉', 'FI', 'R', 'VG', '18K白金', 'images/dr_temp/9.jpg', 'Cras lobortis at tortor nulla magnis Mauris interdum varius sem interdum parturient euismod senectus sit sociis sem Proin pellentesque consequat dolor viverra dolor pretium Nunc rhoncus laoreet nisi velit aliquet bibendum eleifend adipiscing enim nascetur Quisque ad sociosqu sollicitudin lacus ac', '');
INSERT INTO drmessage VALUES ('42', '周大福', 'ultrices', '2619', '5555', '2*2', '11', '5分', 'VVS', 'K', 'G', 'PT950', 'images/dr_temp/4.jpg', 'tempor posuere litora dui aptent purus sollicitudin montes nunc primis lacinia parturient ut nascetur rhoncus tincidunt feugiat amet porta nonummy Maecenas felis sodales parturient eu eros tempus magna molestie sed pharetra nonummy fames dignissim pede luctus elit erat lobortis magnis egestas mus eget laoreet Pellentesque Aliquam egestas In', '');
INSERT INTO drmessage VALUES ('43', '周大生', 'sollicitudin', '46895', '5609', '1*1', '59', '10分', 'I', 'K', 'VG', '18K白金', 'images/dr_temp/7.jpg', 'Class sit scelerisque ipsum Pellentesque elit dictum sociis dapibus Curabitur semper metus vitae elementum sollicitudin metus Donec Nam in et Sed lobortis viverra primis vulputate nunc quis lobortis urna nisi turpis lacus est et metus ipsum fames tincidunt velit tincidunt inceptos Class id cursus litora vehicula nascetur non', '');
INSERT INTO drmessage VALUES ('44', '周大福', 'metus', '56334', '2149', '2*1', '2', '40分', 'IF', 'G', 'VG', '18K黄金', 'images/dr_temp/1.jpg', 'tellus fringilla Ut senectus turpis malesuada tellus Curae dui Mauris feugiat elementum sociosqu et tempor dictum amet taciti massa nascetur sollicitudin ligula purus molestie Class arcu commodo aliquam litora vitae libero feugiat magnis tincidunt feugiat amet viverra placerat ultricies urna hymenaeos Duis pretium nonummy Donec Praesent adipiscing nec cursus', '');
INSERT INTO drmessage VALUES ('45', '周大福', 'pretium', '38933', '4218', '2*2', '46', '40分', 'IF', 'I', 'VG', '18K黄金', 'images/dr_temp/9.jpg', 'natoque penatibus Cras tempus habitant nisl eu velit pharetra ac malesuada morbi condimentum purus mus pharetra commodo pulvinar netus arcu consectetuer scelerisque tortor semper amet In viverra metus', '');
INSERT INTO drmessage VALUES ('46', '周大福', 'commodo', '38745', '267', '1*1', '36', '30分', 'VVS', 'J', 'VG', '18K白金', 'images/dr_temp/7.jpg', 'In nisi Duis turpis Curabitur eleifend lectus ad lobortis ipsum nulla eu orci nostra mattis diam Praesent Class venenatis in vulputate ad fringilla velit ullamcorper tincidunt Suspendisse In dignissim Phasellus sed massa odio magna in odio magna iaculis Suspendisse magna id torquent ornare in diam mauris dictum tempor ornare cursus', '');
INSERT INTO drmessage VALUES ('47', '周大生', 'torquent', '3141', '2719', '2*1', '78', '2克拉', 'I', 'E', 'G', '18K玫瑰金', 'images/dr_temp/1.jpg', 'eleifend mollis metus Aenean natoque ultrices Suspendisse conubia natoque Sed ridiculus egestas pharetra Proin quam bibendum senectus libero In lacinia scelerisque aliquam fames vestibulum Fusce feugiat tempor dis suscipit enim lectus lacus cubilia volutpat vestibulum tristique ac bibendum facilisi dictum Nunc feugiat tempus ornare', '');
INSERT INTO drmessage VALUES ('48', '周大福', 'risus', '16708', '3421', '1*1', '70', '1克拉', 'IF', 'P', 'VG', '18K白金', 'images/dr_temp/6.jpg', 'Suspendisse porttitor sapien odio penatibus imperdiet orci ultrices lacinia fames Nam Vestibulum auctor congue habitant tincidunt Pellentesque sagittis litora mattis Vivamus eu pretium congue Nullam Nam felis euismod consequat porta mus vestibulum hymenaeos lacus tempus Nulla semper et est ultricies gravida interdum ridiculus lectus Sed nunc diam fermentum vehicula', '');
INSERT INTO drmessage VALUES ('49', '周大福', 'elementum', '89571', '9285', '2*1', '23', '30分', 'FI', 'L', 'G', '18K玫瑰金', 'images/dr_temp/8.jpg', 'lacinia conubia et luctus litora magnis luctus ad Proin Class pede vitae vehicula ridiculus fringilla cursus fames quam pretium aliquam condimentum litora ipsum at ultrices volutpat vitae', '');
INSERT INTO drmessage VALUES ('50', '老凤祥', 'Etiam', '25915', '4439', '1*1', '38', '10分', 'VS', 'L', 'G', '18K玫瑰金', 'images/dr_temp/2.jpg', 'faucibus venenatis nunc Aenean aptent vel felis eleifend primis tincidunt turpis primis libero Ut senectus libero eros malesuada sapien Etiam rhoncus torquent per accumsan posuere Aenean torquent morbi aliquam arcu primis Nam Quisque laoreet tempor penatibus tortor pellentesque nibh Curae commodo venenatis eros Cras ad et', '');
